[package]
name = "virtiod"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Reusable asynchronous virtio device implementations"
readme = "README.md"
repository = "https://github.com/lileding/virtiod"
homepage = "https://github.com/lileding/virtiod"
keywords = ["virtio", "virtualization", "vmm"]
categories = ["asynchronous", "virtualization"]

[features]
default = ["full"]
block = []
console = []
fs = []
memory = []
network = []
rng = []
vsock = []
container = ["block", "network", "vsock", "fs"]
vm = ["block", "console", "network", "rng"]
full = ["container", "vm"]

[dependencies]
async-trait = "0.1"
futures-util = "0.3"
libc = "0.2"
thiserror = "2"
tokio = { version = "1", features = ["fs", "io-util", "macros", "rt", "sync"] }

[lib]
crate-type = ["rlib", "cdylib"]
